on:
  release:
    types: [created]
name: Handle Release
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.7
    - name: Build kg and kgctl for all Linux Architectures
      run: make all-build
    - name: Publish Release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'bin/linux/*/kgctl'
